acornfile for django vote app
infracloudio/django-acorn pull request #1
Opened 2023-10-16 12:04 UTC by slayer321

2023-10-23 07:10 UTC, samkulkarni20 requested changes

2023-10-23 07:10 UTC, samkulkarni20 commented on Acornfile
@slayer321 Are you missing a db container in here?

2023-10-23 07:10 UTC, samkulkarni20 commented on docker-compose.yaml
Is it needed by the Acorn? If not let's remove it.

2023-10-23 07:19 UTC, slayer321 commented on Acornfile
No, as on the first line of the Acornfile you can see that I'm using services field . So we are using mariadb DB as the service and not directly , that's why we don't have the db field inside our containers field.

2023-10-23 07:20 UTC, slayer321 commented on docker-compose.yaml
No, not needed. Removing it.

2023-10-26 04:34 UTC, samkulkarni20 approved these changes

2023-10-26 04:34 UTC, merged